---
- hosts: local
  become: yes

  tasks:
    - name: Installation de pycurl pour autoriser apt_repository
      apt:
        name=python-pycurl
        update_cache=yes

    - name: Ajout du repository
      apt_repository:
        repo='deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /'
        state=present

    - name: Ajout de la clé
      apt_key:
        url='https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.key'

    - name: Apt-get update
      apt:
        update_cache=yes

    - name: Installation de ownCloud
      apt:
        name=owncloud
        allow_unauthenticated=yes

    - name: Apache2 DocumentRoot on ownCloud folder
      copy:
        src=owncloud-apache2.conf
        dest=/etc/apache2/sites-available/000-default.conf
        owner=root
        group=root
        mode=0644
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service:
        name=apache2
        state=restarted
