---
- hosts: local
  become: yes

  tasks:
    - name: Installation de pycurl pour authoriser apt_repository
      apt:
        name=python-pycurl
        update_cache=yes

    - name: Ajout du repository
      apt_repository:
        repo='deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /'
        state=present

    - name: Ajout de la clé
      apt_key:
        url='https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.key'

    - name: Apt-get update & Insallation de owncloud
      apt:
        name=owncloud
        update_cache=yes
